### ISSUE TITLE
NPE after rotating tablet while on certain screens

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#149]
To duplicate:

<pre>
Start MAF
Wait for Status page to complete drawing
Select DVR
Wait for Recorded Programs to complete drawing
Rotate tablet 90 degrees
</pre>

Running on: mythtv-android-frontend-1.10.1-405-g881cdcb, Samsung Galaxy 10.1,
Android 4.0.4.

Full LogCat (from start of MAF to NPE.) Note that the failure is at:
08-22 14:33:42.930 or line 1128 in the paste.

http://pastebin.com/nAZiwnW2

I  included the whole log as there are some odd goings on from
lines 86-92.

I didn't capture more logs, but tested other screens with the following results:

<pre>
Status screen fails
Manage Profiles - OK
Upcoming Programs - OK
Recording Rules - switches to Recorded Programs then fails
Guide - same as Recording Rules
</pre>

**Comment by pot8oe** [comment]
I Fixed orientation change for BackendStatusFragment

Status screen - OK
Manage Profiles - OK
Upcoming Programs - OK
Recording Rules - switches to Recorded Programs then fails
Guide - same as Recording Rules

**Comment by pot8oe** [comment]
Fixed orientation for DVR fragments.

Please test on All size devices. I fixed and tested on a HTC One.

Status screen - OK
Manage Profiles - OK
Upcoming Programs - OK
Recording Rules - OK
Guide - OK

**Comment by billmeek** [comment]
Significantly better, but not fixed. The failure has changed:

<pre>
08-24 13:05:58.778: W/dalvikvm(17626): threadid=1: thread exiting with uncaught exception (group=0x40c5b1f8)
08-24 13:05:58.778: E/AndroidRuntime(17626): FATAL EXCEPTION: main
08-24 13:05:58.778: E/AndroidRuntime(17626): java.lang.RuntimeException: ProgramDaoHelper is not initialized
...
</pre>

To duplicate:

<pre>
Go to the Recordings screen
Go to the Guide screen
Rotate the Guide 90 degrees and back again.
</pre>

I've had to repeat the last step as many as five times for the exception to fire.
As always, glad open a new issue if you'd prefer (and provide new LogCat if
I'm the only one who can duplicate it.)

**Comment by dmfrey** [comment]
@billmeek  after repeated attempts to try to reproduce it on my nexus 7, i cannot manage to reproduce it.

**Comment by billmeek** [comment]
@dmfrey, I'm unable to duplicate now as well.
@pot8oe I only have Samsung Galaxy Tab 10.1 and haven't been able to find a way to 
rotate the screen using the Android emulators.

Closing, but anyone else reading, please comment on this issue if you can duplicate the
issue as described in the initial comment on this page. Thanks!

**Comment by pot8oe** [comment]
@billmeek  Switch to next layout orientation (for example, portrait,
landscape) KEYPAD_9, Ctrl-F12
http://developer.android.com/tools/help/emulator.html#KeyMapping

-Tom

**Comment by billmeek** [comment]
Reopening for tracking emulator retests.

**Comment by pot8oe** [comment]
I just tested the latest revision on a Samsung Galaxy Tab plus 7" running Android 4.0.4 and HTC One Running Android 4.3. I did allot of rotations while moving about the application and did not receive a single crash. I'm closing for now and reopen if an orientation change crash is encountered.
